### ISSUE TITLE
Add support to work with Electron 21

### ISSUE THREAD

**Issue by saeta-eth** [max-mapper/menubar#381]
### Description

Not sure why it's not working with Electron 21 but I guess it's related to this line https://github.com/maxogden/menubar/blob/master/package.json#L61

### Steps to Reproduce the Problem

1- Install latest Electron version
2- Try to install menubar

### Expected Behaviour

Menubar installed properly and working with Electron 21

### Actual Behaviour

```
npm i menubar   
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nn@1.0.0
npm ERR! Found: electron@21.0.1
npm ERR! node_modules/electron
npm ERR!   dev electron@"^21.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer electron@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0 || ^19.0.0 || ^20.0.0" from menubar@9.2.2
npm ERR! node_modules/menubar
npm ERR!   menubar@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/slorenzo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/slorenzo/.npm/_logs/2022-10-04T15_17_19_694Z-debug-0.log
```

### Specifications

- Menubar version: latest
- Platform: Macbook m1
- Electron version: 21

Thanks for this incredible package, I have used this in the past and was a great.

**Comment by amaurym** [comment]
@saeta-eth Would you like to create a PR, similar to https://github.com/maxogden/menubar/pull/379 ?

**Comment by saeta-eth** [comment]
@amaurym Ofc, would you like to review https://github.com/maxogden/menubar/pull/382?
